using IdleKingdomsEditor.DataObjects;

namespace IdleKingdomsEditor
{
    class KnownCoordinates
    {
        public static HexCell[] Forests() => new[]
        {
            new HexCell { Row = 0,Col = 23},
            new HexCell { Row = 0,Col = 24},
            new HexCell { Row = 0,Col = 27},
            new HexCell { Row = 1,Col = 14},
            new HexCell { Row = 1,Col = 18},
            new HexCell { Row = 1,Col = 19},
            new HexCell { Row = 1,Col = 21},
            new HexCell { Row = 1,Col = 22},
            new HexCell { Row = 2,Col = 18},
            new HexCell { Row = 2,Col = 21},
            new HexCell { Row = 2,Col = 24},
            new HexCell { Row = 2,Col = 27},
            new HexCell { Row = 3,Col = 15},
            new HexCell { Row = 3,Col = 19},
            new HexCell { Row = 3,Col = 21},
            new HexCell { Row = 3,Col = 27},
            new HexCell { Row = 3,Col = 29},
            new HexCell { Row = 4,Col = 13},
            new HexCell { Row = 4,Col = 21},
            new HexCell { Row = 4,Col = 24},
            new HexCell { Row = 4,Col = 26},
            new HexCell { Row = 4,Col = 30},
            new HexCell { Row = 5,Col = 8},
            new HexCell { Row = 5,Col = 15},
            new HexCell { Row = 5,Col = 16},
            new HexCell { Row = 5,Col = 23},
            new HexCell { Row = 5,Col = 26},
            new HexCell { Row = 6,Col = 7},
            new HexCell { Row = 6,Col = 10},
            new HexCell { Row = 6,Col = 11},
            new HexCell { Row = 6,Col = 31},
            new HexCell { Row = 7,Col = 12},
            new HexCell { Row = 7,Col = 13},
            new HexCell { Row = 7,Col = 27},
            new HexCell { Row = 8,Col = 9},
            new HexCell { Row = 8,Col = 10},
            new HexCell { Row = 8,Col = 13},
            new HexCell { Row = 8,Col = 15},
            new HexCell { Row = 8,Col = 25},
            new HexCell { Row = 8,Col = 31},
            new HexCell { Row = 8,Col = 33},
            new HexCell { Row = 9,Col = 16},
            new HexCell { Row = 9,Col = 17},
            new HexCell { Row = 9,Col = 20},
            new HexCell { Row = 9,Col = 24},
            new HexCell { Row = 9,Col = 25},
            new HexCell { Row = 10,Col = 5},
            new HexCell { Row = 10,Col = 10},
            new HexCell { Row = 10,Col = 11},
            new HexCell { Row = 10,Col = 13},
            new HexCell { Row = 10,Col = 21},
            new HexCell { Row = 10,Col = 29},
            new HexCell { Row = 10,Col = 33},
            new HexCell { Row = 11,Col = 15},
            new HexCell { Row = 11,Col = 16},
            new HexCell { Row = 11,Col = 22},
            new HexCell { Row = 11,Col = 23},
            new HexCell { Row = 11,Col = 34},
            new HexCell { Row = 12,Col = 34},
            new HexCell { Row = 13,Col = 3},
            new HexCell { Row = 13,Col = 10},
            new HexCell { Row = 13,Col = 13},
            new HexCell { Row = 13,Col = 14},
            new HexCell { Row = 13,Col = 20},
            new HexCell { Row = 13,Col = 30},
            new HexCell { Row = 13,Col = 34},
            new HexCell { Row = 14,Col = 9},
            new HexCell { Row = 14,Col = 12},
            new HexCell { Row = 14,Col = 13},
            new HexCell { Row = 14,Col = 17},
            new HexCell { Row = 14,Col = 23},
            new HexCell { Row = 14,Col = 27},
            new HexCell { Row = 14,Col = 32},
            new HexCell { Row = 15,Col = 10},
            new HexCell { Row = 15,Col = 13},
            new HexCell { Row = 15,Col = 20},
            new HexCell { Row = 15,Col = 26},
            new HexCell { Row = 15,Col = 36},
            new HexCell { Row = 16,Col = 5},
            new HexCell { Row = 16,Col = 6},
            new HexCell { Row = 16,Col = 11},
            new HexCell { Row = 16,Col = 15},
            new HexCell { Row = 16,Col = 27},
            new HexCell { Row = 16,Col = 35},
            new HexCell { Row = 17,Col = 3},
            new HexCell { Row = 17,Col = 13},
            new HexCell { Row = 17,Col = 19},
            new HexCell { Row = 17,Col = 25},
            new HexCell { Row = 17,Col = 27},
            new HexCell { Row = 18,Col = 10},
            new HexCell { Row = 18,Col = 23},
            new HexCell { Row = 18,Col = 24},
            new HexCell { Row = 18,Col = 28},
            new HexCell { Row = 19,Col = 6},
            new HexCell { Row = 19,Col = 8},
            new HexCell { Row = 19,Col = 15},
            new HexCell { Row = 19,Col = 29},
            new HexCell { Row = 19,Col = 37},
            new HexCell { Row = 20,Col = 7},
            new HexCell { Row = 20,Col = 17},
            new HexCell { Row = 20,Col = 21},
            new HexCell { Row = 20,Col = 23},
            new HexCell { Row = 20,Col = 25},
            new HexCell { Row = 20,Col = 26},
            new HexCell { Row = 20,Col = 27},
            new HexCell { Row = 20,Col = 29},
            new HexCell { Row = 20,Col = 32},
            new HexCell { Row = 20,Col = 34},
            new HexCell { Row = 21,Col = 4},
            new HexCell { Row = 21,Col = 10},
            new HexCell { Row = 21,Col = 11},
            new HexCell { Row = 21,Col = 14},
            new HexCell { Row = 21,Col = 15},
            new HexCell { Row = 21,Col = 17},
            new HexCell { Row = 21,Col = 21},
            new HexCell { Row = 21,Col = 24},
            new HexCell { Row = 21,Col = 27},
            new HexCell { Row = 21,Col = 33},
            new HexCell { Row = 21,Col = 37},
            new HexCell { Row = 22,Col = 3},
            new HexCell { Row = 22,Col = 8},
            new HexCell { Row = 22,Col = 12},
            new HexCell { Row = 22,Col = 18},
            new HexCell { Row = 22,Col = 19},
            new HexCell { Row = 22,Col = 20},
            new HexCell { Row = 22,Col = 22},
            new HexCell { Row = 22,Col = 33},
            new HexCell { Row = 22,Col = 34},
            new HexCell { Row = 22,Col = 35},
            new HexCell { Row = 22,Col = 37},
            new HexCell { Row = 23,Col = 5},
            new HexCell { Row = 23,Col = 6},
            new HexCell { Row = 23,Col = 8},
            new HexCell { Row = 23,Col = 9},
            new HexCell { Row = 23,Col = 20},
            new HexCell { Row = 23,Col = 22},
            new HexCell { Row = 23,Col = 23},
            new HexCell { Row = 23,Col = 26},
            new HexCell { Row = 24,Col = 8},
            new HexCell { Row = 24,Col = 13},
            new HexCell { Row = 24,Col = 21},
            new HexCell { Row = 24,Col = 24},
            new HexCell { Row = 24,Col = 25},
            new HexCell { Row = 24,Col = 30},
            new HexCell { Row = 24,Col = 36},
            new HexCell { Row = 25,Col = 6},
            new HexCell { Row = 25,Col = 9},
            new HexCell { Row = 25,Col = 12},
            new HexCell { Row = 25,Col = 17},
            new HexCell { Row = 25,Col = 21},
            new HexCell { Row = 25,Col = 22},
            new HexCell { Row = 25,Col = 24},
            new HexCell { Row = 25,Col = 25},
            new HexCell { Row = 25,Col = 26},
            new HexCell { Row = 25,Col = 31},
            new HexCell { Row = 26,Col = 5},
            new HexCell { Row = 26,Col = 6},
            new HexCell { Row = 26,Col = 21},
            new HexCell { Row = 26,Col = 23},
            new HexCell { Row = 26,Col = 26},
            new HexCell { Row = 26,Col = 29},
            new HexCell { Row = 26,Col = 31},
            new HexCell { Row = 27,Col = 5},
            new HexCell { Row = 27,Col = 8},
            new HexCell { Row = 27,Col = 14},
            new HexCell { Row = 27,Col = 23},
            new HexCell { Row = 27,Col = 24},
            new HexCell { Row = 27,Col = 30},
            new HexCell { Row = 27,Col = 34},
            new HexCell { Row = 28,Col = 6},
            new HexCell { Row = 28,Col = 22},
            new HexCell { Row = 28,Col = 24},
            new HexCell { Row = 29,Col = 9},
            new HexCell { Row = 29,Col = 14},
            new HexCell { Row = 29,Col = 15},
            new HexCell { Row = 29,Col = 33},
            new HexCell { Row = 30,Col = 6},
            new HexCell { Row = 30,Col = 8},
            new HexCell { Row = 30,Col = 12},
            new HexCell { Row = 30,Col = 18},
            new HexCell { Row = 30,Col = 19},
            new HexCell { Row = 30,Col = 20},
            new HexCell { Row = 31,Col = 6},
            new HexCell { Row = 31,Col = 7},
            new HexCell { Row = 31,Col = 16},
            new HexCell { Row = 31,Col = 18},
            new HexCell { Row = 32,Col = 9},
            new HexCell { Row = 32,Col = 15},
            new HexCell { Row = 32,Col = 23},
            new HexCell { Row = 33,Col = 7},
            new HexCell { Row = 33,Col = 8},
            new HexCell { Row = 33,Col = 19},
            new HexCell { Row = 33,Col = 23},
            new HexCell { Row = 33,Col = 26},
            new HexCell { Row = 34,Col = 14},
            new HexCell { Row = 34,Col = 16},
            new HexCell { Row = 34,Col = 23},
            new HexCell { Row = 34,Col = 25},
            new HexCell { Row = 34,Col = 31},
            new HexCell { Row = 35,Col = 27},
            new HexCell { Row = 35,Col = 28},
            new HexCell { Row = 36,Col = 13},
            new HexCell { Row = 37,Col = 19},
            new HexCell { Row = 37,Col = 22},
            new HexCell { Row = 37,Col = 23},
            new HexCell { Row = 38,Col = 12},
            new HexCell { Row = 38,Col = 20},
            new HexCell { Row = 38,Col = 22}
        };

        public static HexCell[] Water() => new[]
        {
            new HexCell { Row = 14,Col = 19},
            new HexCell { Row = 14,Col = 20},
            new HexCell { Row = 14,Col = 21},
            new HexCell { Row = 15,Col = 18},
            new HexCell { Row = 15,Col = 19},
            new HexCell { Row = 16,Col = 25},
            new HexCell { Row = 16,Col = 26},
            new HexCell { Row = 17,Col = 24},
            new HexCell { Row = 17,Col = 26},
            new HexCell { Row = 18,Col = 25},
            new HexCell { Row = 18,Col = 26},
            new HexCell { Row = 19,Col = 17},
            new HexCell { Row = 20,Col = 18},
            new HexCell { Row = 20,Col = 19},
            new HexCell { Row = 21,Col = 18},
            new HexCell { Row = 21,Col = 19},
            new HexCell { Row = 21,Col = 20},
            new HexCell { Row = 22,Col = 21},
            new HexCell { Row = 23,Col = 21},
            new HexCell { Row = 24,Col = 22},
            new HexCell { Row = 24,Col = 23},
            new HexCell { Row = 25,Col = 23},
            new HexCell { Row = 26,Col = 24},
            new HexCell { Row = 26,Col = 25},
            new HexCell { Row = 27,Col = 25},
            new HexCell { Row = 28,Col = 26},
            new HexCell { Row = 28,Col = 27},
            new HexCell { Row = 28,Col = 28},
            new HexCell { Row = 29,Col = 25},
            new HexCell { Row = 29,Col = 26},
            new HexCell { Row = 29,Col = 27},
            new HexCell { Row = 29,Col = 28},
            new HexCell { Row = 30,Col = 26},
            new HexCell { Row = 30,Col = 27},
            new HexCell { Row = 30,Col = 28},
            new HexCell { Row = 30,Col = 29},
            new HexCell { Row = 31,Col = 26},
            new HexCell { Row = 31,Col = 27},
            new HexCell { Row = 31,Col = 28}
        };

        public static HexCell[] Sand() => new[]
        {
            new HexCell { Row = 18,Col = 20},
            new HexCell { Row = 19,Col = 20},
            new HexCell { Row = 20,Col = 20},
            new HexCell { Row = 27,Col = 26},
            new HexCell { Row = 27,Col = 27},
            new HexCell { Row = 27,Col = 28},
            new HexCell { Row = 28,Col = 25},
            new HexCell { Row = 28,Col = 29},
            new HexCell { Row = 29,Col = 24},
            new HexCell { Row = 29,Col = 29},
            new HexCell { Row = 30,Col = 25},
            new HexCell { Row = 30,Col = 30},
            new HexCell { Row = 31,Col = 25},
            new HexCell { Row = 31,Col = 29},
            new HexCell { Row = 32,Col = 26},
            new HexCell { Row = 32,Col = 27},
            new HexCell { Row = 32,Col = 28},
            new HexCell { Row = 32,Col = 29}
        };

        public static HexCell[] Mountains() => new[]
        {
            new HexCell { Row = 15,Col = 17},
            new HexCell { Row = 15,Col = 21},
            new HexCell { Row = 16,Col = 17},
            new HexCell { Row = 16,Col = 18},
            new HexCell { Row = 16,Col = 21},
            new HexCell { Row = 16,Col = 22},
            new HexCell { Row = 17,Col = 16},
            new HexCell { Row = 17,Col = 17},
            new HexCell { Row = 17,Col = 21},
            new HexCell { Row = 18,Col = 17},
            new HexCell { Row = 18,Col = 18},
            new HexCell { Row = 18,Col = 35},
            new HexCell { Row = 18,Col = 36},
            new HexCell { Row = 19,Col = 16},
            new HexCell { Row = 19,Col = 34},
            new HexCell { Row = 20,Col = 36}
        };

        public static ShrineCell[] Shrines() => new[]
        {
            new ShrineCell { Row = 2, Col = 13, PrestigeMultiplier = 2, FoodMultiplier = 2 },
            new ShrineCell { Row = 4, Col = 25, PrestigeMultiplier = 6, FoodMultiplier = 3 },
            new ShrineCell { Row = 6, Col = 14, FoodCartMultiplier = 4 },
            new ShrineCell { Row = 7, Col = 21, AllCartMultiplier = 2 },
            new ShrineCell { Row = 7, Col = 24, FoodCartMultiplier = 3 },
            new ShrineCell { Row = 8, Col = 19, WoodMultiplier = 2 },
            new ShrineCell { Row = 9, Col = 15, PrestigeMultiplier = 4, FoodMultiplier = 2 },
            new ShrineCell { Row = 9, Col = 22, PrestigeMultiplier = 1.5, FoodMultiplier = 1.5 },
            new ShrineCell { Row = 9, Col = 26, ForagingHutMultiplier = 3 },
            new ShrineCell { Row = 10, Col = 7, PrestigeMultiplier = 6, FoodMultiplier = 2 },
            new ShrineCell { Row = 11, Col = 18, PrestigeMultiplier = 2.5, AllCartMultiplier = 1.5 },
            new ShrineCell { Row = 11, Col = 27, PrestigeMultiplier = 2, AllCartMultiplier = 2 },
            new ShrineCell { Row = 12, Col = 11, PrestigeMultiplier = 4, FoodMultiplier = 2 },
            new ShrineCell { Row = 12, Col = 14, PrestigeMultiplier = 2.5, ScienceMultiplier = 3 },
            new ShrineCell { Row = 12, Col = 25, PrestigeMultiplier = 1.5, FoodMultiplier = 2 },
            new ShrineCell { Row = 12, Col = 31, PrestigeMultiplier = 5 },
            new ShrineCell { Row = 12, Col = 32, FoodCartMultiplier = 3 },
            new ShrineCell { Row = 13, Col = 21, FoodMultiplier = 2.5 },
            new ShrineCell { Row = 14, Col = 24, FoodCartMultiplier = 5 },
            new ShrineCell { Row = 14, Col = 28, FoodMultiplier = 3 },
            new ShrineCell { Row = 16, Col = 14, FoodCartMultiplier = 4 },
            new ShrineCell { Row = 17, Col = 5, FoodCartMultiplier = 3 },
            new ShrineCell { Row = 17, Col = 12, ScienceMultiplier = 2 },
            new ShrineCell { Row = 17, Col = 18, Content = "FS" },
            new ShrineCell { Row = 17, Col = 20, Content = "F,WC"},
            new ShrineCell { Row = 17, Col = 23, Content = "SP" },
            new ShrineCell { Row = 18, Col = 5, PrestigeMultiplier = 2.5, FoodMultiplier = 2 },
            new ShrineCell { Row = 18, Col = 11, PrestigeMultiplier = 2.5, FoodMultiplier = 2 },
            new ShrineCell { Row = 18, Col = 22, Content = "H" },
            new ShrineCell { Row = 18, Col = 29, WoodCartMultiplier = 2 },
            new ShrineCell { Row = 19, Col = 19 },
            new ShrineCell { Row = 19, Col = 24, ForagingHutMultiplier = 4 },
            new ShrineCell { Row = 21, Col = 22, Content = "SH" },
            new ShrineCell { Row = 21, Col = 26 , Content = "LIB" },
            new ShrineCell { Row = 22, Col = 6, PrestigeMultiplier = 8, FoodMultiplier = 2 },
            new ShrineCell { Row = 22, Col = 29, PrestigeMultiplier = 2 },
            new ShrineCell { Row = 22, Col = 32, PrestigeMultiplier = 3, WoodMultiplier = 2 },
            new ShrineCell { Row = 23, Col = 14, PrestigeMultiplier = 2.5, WoodMultiplier = 2, AllCartMultiplier = 2 },
            new ShrineCell { Row = 23, Col = 19, PrestigeMultiplier = 4, FoodMultiplier = 2 },
            new ShrineCell { Row = 24, Col = 26, FoodCartMultiplier = 2 },
            new ShrineCell { Row = 24, Col = 29, FoodMultiplier = 2 },
            new ShrineCell { Row = 27, Col = 17, FoodCartMultiplier = 2 },
            new ShrineCell { Row = 27, Col = 33, PrestigeMultiplier = 2.5, FoodMultiplier = 3 },
            new ShrineCell { Row = 28, Col = 14, PrestigeMultiplier = 4, FoodMultiplier = 2 },
            new ShrineCell { Row = 28, Col = 21, PrestigeMultiplier = 4, FoodMultiplier = 3 },
            new ShrineCell { Row = 29, Col = 31, PrestigeMultiplier = 4 },
            new ShrineCell { Row = 33, Col = 24, FoodMultiplier = 6 },
            new ShrineCell { Row = 34, Col = 21, PrestigeMultiplier = 6 },
            new ShrineCell { Row = 34, Col = 28, PrestigeMultiplier = 6, FoodMultiplier = 2 },
            new ShrineCell { Row = 36, Col = 14, PrestigeMultiplier = 3.5, FoodMultiplier = 2 }
        };
    }
}
